import { readFile, writeFile, stat } from "node:fs/promises";
import { join } from "node:path";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import * as z from "zod";
import { analyzeDependencies } from "../analyzers/dependencies.js";
import { analyzeStructure } from "../analyzers/structure.js";
import { detectFramework, detectStack } from "../analyzers/detection.js";
import { analyzePatterns } from "../analyzers/patterns.js";
import { resolveAndFetch, TECH_QUERIES } from "../context7/index.js";
import { generateClaudeMd } from "../templates/claude-md.js";
import type { RepoAnalysis } from "../types.js";
import type { FetchedDocs } from "./fetch-docs.js";

/**
 * Extract user-added sections from an existing CLAUDE.md.
 * Preserves "Project Decisions" and any section not generated by LeadCode.
 */
function extractUserChoices(existingContent: string): Record<string, string> {
  const choices: Record<string, string> = {};
  const decisionsMatch = existingContent.match(
    /## Project Decisions\n+([\s\S]*?)(?=\n## |$)/
  );
  if (decisionsMatch) {
    const lines = decisionsMatch[1].trim().split("\n");
    for (const line of lines) {
      const m = line.match(/^- \*\*(.+?)\*\*: (.+)$/);
      if (m) {
        choices[m[1]] = m[2];
      }
    }
  }
  return choices;
}

/** Collect techs and fetch docs (same logic as fetch-docs tool but inline) */
async function fetchDocsForAnalysis(analysis: RepoAnalysis): Promise<FetchedDocs> {
  const techs: string[] = [];
  if (analysis.framework) techs.push(analysis.framework.name);
  const d = analysis.detected;
  for (const value of Object.values(d)) {
    if (typeof value === "string") techs.push(value);
  }
  const uniqueTechs = [...new Set(techs)];

  const techDocs: Record<string, string> = {};
  const crossDocs: Record<string, string> = {};
  const failedTechs: string[] = [];
  let snippetCount = 0;

  for (const tech of uniqueTechs) {
    const mapping = TECH_QUERIES[tech];
    if (!mapping) { failedTechs.push(tech); continue; }
    const docs = await resolveAndFetch(mapping.libraryName, mapping.queries.join(". "));
    if (docs) { techDocs[tech] = docs; snippetCount++; }
    else { failedTechs.push(tech); }
  }

  for (const tech of uniqueTechs) {
    const mapping = TECH_QUERIES[tech];
    if (!mapping?.crossQueries) continue;
    for (const [other, query] of Object.entries(mapping.crossQueries)) {
      if (!uniqueTechs.includes(other)) continue;
      const key = `${tech}+${other}`;
      const rev = `${other}+${tech}`;
      if (key in crossDocs || rev in crossDocs) continue;
      const docs = await resolveAndFetch(mapping.libraryName, query);
      if (docs) { crossDocs[key] = docs; snippetCount++; }
    }
  }

  return {
    techDocs,
    crossDocs,
    metadata: { techCount: Object.keys(techDocs).length, snippetCount, failedTechs },
  };
}

export function registerUpdateClaudeMd(server: McpServer): void {
  server.registerTool(
    "update-claude-md",
    {
      title: "Update CLAUDE.md",
      description:
        "Re-analyzes the project, fetches fresh documentation from Context7, and regenerates CLAUDE.md while preserving user choices from the Project Decisions section.",
      inputSchema: {
        projectPath: z
          .string()
          .describe("Absolute path to the project root directory"),
      },
    },
    async ({ projectPath }) => {
      try {
        try {
          await stat(projectPath);
        } catch {
          return {
            isError: true,
            content: [{ type: "text" as const, text: `Project directory not found: ${projectPath}` }],
          };
        }

        const claudeMdPath = join(projectPath, "CLAUDE.md");

        // Extract existing choices if CLAUDE.md exists
        let previousChoices: Record<string, string> = {};
        try {
          const existing = await readFile(claudeMdPath, "utf-8");
          previousChoices = extractUserChoices(existing);
        } catch {
          // No existing file — that's fine
        }

        // Re-analyze
        const pkg = await analyzeDependencies(projectPath);
        const structure = await analyzeStructure(projectPath);
        const framework = detectFramework(pkg.dependencies, pkg.devDependencies, structure);
        const detected = detectStack(pkg.dependencies, pkg.devDependencies);
        detected.runtime = structure.detectedRuntime;
        const patterns = await analyzePatterns(projectPath);

        const analysis: RepoAnalysis = {
          projectPath,
          projectName: pkg.name,
          framework,
          dependencies: pkg.dependencies,
          devDependencies: pkg.devDependencies,
          scripts: pkg.scripts,
          structure,
          detected,
        };

        // Fetch fresh docs
        const docs = await fetchDocsForAnalysis(analysis);

        const content = generateClaudeMd(
          analysis,
          docs,
          previousChoices,
          patterns
        );

        await writeFile(claudeMdPath, content, "utf-8");

        return {
          content: [
            {
              type: "text" as const,
              text: JSON.stringify(
                {
                  path: claudeMdPath,
                  message: "CLAUDE.md updated successfully",
                  preservedChoices: Object.keys(previousChoices).length,
                  stats: {
                    techDocs: Object.keys(docs.techDocs).length,
                    crossDocs: Object.keys(docs.crossDocs).length,
                    failedTechs: docs.metadata.failedTechs,
                  },
                },
                null,
                2
              ),
            },
          ],
        };
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        return {
          isError: true,
          content: [{ type: "text" as const, text: `update-claude-md failed: ${message}` }],
        };
      }
    }
  );
}
