import { readFile, writeFile, stat } from "node:fs/promises";
import { join } from "node:path";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import * as z from "zod";
import { analyzeDependencies } from "../analyzers/dependencies.js";
import { analyzeStructure } from "../analyzers/structure.js";
import { detectFramework, detectStack } from "../analyzers/detection.js";
import { analyzePatterns } from "../analyzers/patterns.js";
import {
  getConventions,
  getInterdictions,
  getActiveCrossRefs,
} from "../rules/index.js";
import { generateClaudeMd } from "../templates/claude-md.js";
import type { RepoAnalysis } from "../types.js";
import type { Locale } from "../i18n/types.js";
import { getMessages, interpolate } from "../i18n/index.js";

/**
 * Extract user-added sections from an existing CLAUDE.md.
 * Preserves "Project Decisions" and any section not generated by LeadCode.
 */
function extractUserChoices(existingContent: string): Record<string, string> {
  const choices: Record<string, string> = {};
  // Match both English and French section headers
  const decisionsMatch = existingContent.match(
    /## (?:Project Decisions|Décisions du projet)\n+([\s\S]*?)(?=\n## |$)/
  );
  if (decisionsMatch) {
    const lines = decisionsMatch[1].trim().split("\n");
    for (const line of lines) {
      const m = line.match(/^- \*\*(.+?)\*\*: (.+)$/);
      if (m) {
        choices[m[1]] = m[2];
      }
    }
  }
  return choices;
}

/** Detect locale of existing CLAUDE.md by checking for French section headers */
function detectExistingLocale(content: string): Locale {
  if (content.includes("## Vue d'ensemble") || content.includes("## Stack technique") || content.includes("## Décisions du projet")) {
    return "fr";
  }
  return "en";
}

export function registerUpdateClaudeMd(server: McpServer): void {
  server.registerTool(
    "update-claude-md",
    {
      title: "Update CLAUDE.md",
      description:
        "Re-analyzes the project and regenerates CLAUDE.md while preserving user choices from the Project Decisions section. Use this after adding dependencies, changing structure, or updating the stack.",
      inputSchema: {
        projectPath: z
          .string()
          .describe("Absolute path to the project root directory"),
        language: z
          .enum(["en", "fr"])
          .optional()
          .describe("Output language. If omitted, keeps the language of the existing CLAUDE.md (default: en for new files)"),
      },
    },
    async ({ projectPath, language }) => {
      try {
        // Verify project path
        try {
          await stat(projectPath);
        } catch {
          const msg = getMessages(language ?? "en");
          return {
            isError: true,
            content: [{ type: "text" as const, text: interpolate(msg.tools.dirNotFound, { path: projectPath }) }],
          };
        }

        const claudeMdPath = join(projectPath, "CLAUDE.md");

        // Extract existing choices and detect locale if CLAUDE.md exists
        let previousChoices: Record<string, string> = {};
        let detectedLocale: Locale = "en";
        try {
          const existing = await readFile(claudeMdPath, "utf-8");
          previousChoices = extractUserChoices(existing);
          detectedLocale = detectExistingLocale(existing);
        } catch {
          // No existing file — that's fine
        }

        const locale: Locale = language ?? detectedLocale;
        const msg = getMessages(locale);

        // Re-analyze
        const pkg = await analyzeDependencies(projectPath);
        const structure = await analyzeStructure(projectPath);
        const framework = detectFramework(pkg.dependencies, pkg.devDependencies, structure);
        const detected = detectStack(pkg.dependencies, pkg.devDependencies);
        detected.runtime = structure.detectedRuntime;
        const patterns = await analyzePatterns(projectPath);

        const analysis: RepoAnalysis = {
          projectPath,
          projectName: pkg.name,
          framework,
          dependencies: pkg.dependencies,
          devDependencies: pkg.devDependencies,
          scripts: pkg.scripts,
          structure,
          detected,
        };

        const conventions = getConventions(analysis);
        const interdictions = getInterdictions(analysis);
        const crossRefs = getActiveCrossRefs(analysis);

        const content = generateClaudeMd(
          analysis,
          conventions,
          interdictions,
          crossRefs,
          previousChoices,
          patterns,
          locale
        );

        await writeFile(claudeMdPath, content, "utf-8");

        return {
          content: [
            {
              type: "text" as const,
              text: JSON.stringify(
                {
                  path: claudeMdPath,
                  message: msg.tools.updateSuccess,
                  language: locale,
                  preservedChoices: Object.keys(previousChoices).length,
                  sections: {
                    conventions: conventions.length,
                    interdictions: interdictions.length,
                    crossStackRules: crossRefs.length,
                  },
                },
                null,
                2
              ),
            },
          ],
        };
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        return {
          isError: true,
          content: [{ type: "text" as const, text: `update-claude-md failed: ${message}` }],
        };
      }
    }
  );
}
